# Using https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/ to
# help customize tmux. Thanks!

# config reload
bind R source-file ~/.tmux.conf \; display-message " Config reloaded..".

# Some global settings
set-option -g allow-rename off
set-option -g monitor-activity on
set-option -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1
set -g default-terminal "tmux-256color"

# Window split commands
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Pane navigation
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Other bindings
bind -n C-M-s setw synchronize-panes

# Mouse support
set -g mouse on

# Copy mode
set -g mode-keys vi

# Clipboard
set -g copy-command 'wl-copy'
