# Using https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/ to
# help customize tmux. Thanks!
#
# My config is evolving though. I'm moving more towards using defaults and
# only override a default if it's problematic or drives me crazy. This is
# very subjective, of course.

# Need to learn more about this one. What are the full set of choices?
# And do I need to sync this with my bash setting? And how is nvim 
# impacted?
#
# `toe -a | grep tmux` will show an explanation of choices.
# `tree /usr/share/terminfo | grep tmux` will show the raw values
set -g default-terminal "tmux-256color"

# Config reload. This comes in handy when I'm fiddling with my tmux config
bind R source-file ~/.tmux.conf \; display-message " Config reloaded..".

# I'm rebinding window splits so that I can have them open in the 
# same directory as the pane I'm splitting from
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# I use synchronize panes a lot. This is a handy shortcut for me
bind -n C-M-s setw synchronize-panes

# I like to name windows and don't want tmux to automatically 
# rename them. allow-rename off stops tmux from doing so.
set-option -g allow-rename off

# When I close a window I want the numbers to be updated and I want to
# start at 1 instead of 0
set-option -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1

# Pane navigation
# I'm keeping these because I navigate panes frequently. Pressing ctrl+b first
# is too much reach for my hands. So in this case I'm making an exception to
# my use default mapping rules
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Mouse support
set -g mouse on

# Copy mode
set -g mode-keys vi

# Clipboard
set -g copy-command 'wl-copy'

# Recently learned about popups and I love them... for certain things.
# Display last, current, and next month
bind-key C-c display-popup -h 20% 'cal -B 1 -A 1'
